### ISSUE TITLE
Error opening x-github-classroom://

### ISSUE THREAD

**Issue by jtppragg** [education/classroom-assistant#86] opened 2018-09-28 11:39 UTC
I have installed the classroom-assistant_1.0.0_amd64.deb release file in Kubuntu 18.04 LTS but after signing in with my account I get an error about not being able to open the following URL:

x-github-classroom://?code=BAh7BzoMd...

![screenshot_20180928_133745](https://user-images.githubusercontent.com/43606299/46206272-bd2e4d00-c323-11e8-86d7-02e674d61bb8.png)

**Comment by srinjoym** [comment] 2018-09-28 17:44
Hi @jtppragg! 👋 

Thanks for downloading Classroom Assistant! There seems to be an issue with the protocol handling on some distributions of Linux. We're currently looking into a solution, I'll update you as soon as we make some progress!

Thanks for your patience! 🙌

**Comment by caw13** [comment] 2018-09-28 21:35
@srinjoym is there a particular Linux configuration that has had success that I can try in the meantime?  I'm having an issue with Ubuntu 18.04 as well that I suspect it's probably the same issue.  Thanks!

**Comment by srinjoym** [comment] 2018-09-30 02:41
@caw13 It looks like there's an issue with setting the protocol handling up in Electron on all distributions of Linux. Working to get a fix out asap, really sorry for the inconvenience!

**Comment by srinjoym** [comment] 2018-10-01 08:11
@jtppragg @caw13 I just released a new version of Classroom Assistant which should fix the problems you guys have been experiencing on Ubuntu 18.04. Let me know if this build seems to be working, once again really sorry for the inconvenience!

Here's the link to the Debian file: https://github.com/education/classroom-assistant/releases/download/v1.0.1/classroom-assistant_1.0.1_amd64.deb

**Comment by jtppragg** [comment] 2018-10-01 09:04
Thank you @srinjoym for your quick response but I am afraid that this fix introduces another problem related to url handling. This console output is shown and the GUI does not start now:

(node:11106) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command failed: xdg-settings set default-url-scheme-handler x-github-classroom classroom-assistant.desktop

(node:11106) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by srinjoym** [comment] 2018-10-01 17:13
@jtppragg Sorry you're still dealing with issues! Are you installing the debian package through the Ubuntu Software Center/some other package installer? Should be able to open Classroom Assistant from your desktop after that install.

The only reason I can think of for that command to be failing is if it cannot find the Classroom Assistant `.desktop` file, which should be installed when the app is installed. 

I can walk through some more debugging steps if this is not an installation issue, might be a Kubuntu specific issue since the app seems to be working fine for me on Ubuntu 18.04

**Comment by jtppragg** [comment] 2018-10-01 17:32
I have successfully installed the deb file form the command line using:
`# dpkg -i classroom-assistant_1.0.1_amd64.deb`

The Kubuntu application launcher also shows the Classroom Assistant app, which is associated to the following *.desktop file:
`$ ls -l /usr/share/applications/classroom-assistant.desktop` 
`-rw-r--r-- 1 root root 229 oct  1 09:48 /usr/share/applications/classroom-assistant.desktop`

But if I try to launch it from the GUI it happens nothing. If I launch it from the command line I get the error:
`$ classroom-assistant`
`(node:3299) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command failed: xdg-settings set default-url-scheme-handler x-github-classroom classroom-assistant.desktop`
`(node:3299) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Finally, If I run the command myself:
`$ xdg-settings set default-url-scheme-handler x-github-classroom classroom-assistant.desktop`
`$ echo $?`
`4`

Which just means "action failed". I could try to see what's the problem with that command.

Thanks!

**Comment by jtppragg** [comment] 2018-10-02 14:15
I think the problem is not related to the url-scheme association:
`$ grep github ~/.config/mimeapps.list`
`x-scheme-handler/x-github-classroom=classroom-assistant.desktop`

And if I execute xdg-open the classroom assistant starts and then fails:
`$ xdg-open x-github-classroom://`
`kf5.kio.core: "preferred service for x-scheme-handler/x-github-classroom" "classroom-assistant"`
`(node:32320) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command failed: xdg-settings set default-url-scheme-handler x-github-classroom classroom-assistant.desktop`
`(node:32320) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code`

Maybe the "solution" is just to handle the promise rejection to just ignore it and go on? ...

**Comment by srinjoym** [comment] 2018-10-03 00:05
@jtppragg Sorry for the delay, thank you so much for the detailed debugging steps!

I downloaded your distribution of Kubuntu and see the same problem. Looks like just handling the error silently should fix the issue. I'll generate a build and test it out on Kubuntu and then bundle the patch with a few more UI fixes coming at the end of the week.

Once again, thanks for your patience! Hopefully Classroom Assistant works smoothly for you after this patch! ✨

**Comment by caw13** [comment] 2018-10-03 02:31
@srinjoym The release you posted earlier in this chain resolved the issue I was having on Ubuntu 18.04, thank you for the quick fix.

**Comment by lizajane999** [comment] 2018-10-05 00:55
I am having the same unhandled promise rejection problem as discussed by @jtppragg in this thread.  Kubuntu 18.04, classroom assistant installed from .deb. I posted a new issue because I didn't see that it was being discussed in this thread until after.

**Comment by srinjoym** [comment] 2018-10-10 16:30
@jtppragg @lizajane999 Just published a new build of Classroom Assistant which catches the error when the `xdg-settings` command fails.

Classroom Assistant also requires `gnome-keyring` when running on Kubuntu, the installation instructions are here: https://github.com/education/classroom-assistant/blob/master/docs/linux-issues.md#kde

Let me know if this build is working better, thanks for all of the help!

**Comment by jtppragg** [comment] 2018-10-11 09:16
@srinjoym now worked successfully!

There is a minor issue that I am not sure if it is related to this one. Now If I click "Download Repositories" from the web page of the assignment, it opens the assistant but I must enter the assignment URL manually. I am not sure whether this is normal or there is an issue dealing with the x-github-classroom:// URL.

Thank you!

**Comment by srinjoym** [comment] 2018-10-17 17:05
Closing this out, @jtppragg feel free to open a separate issue for the URL entering issue. I suspect that's an artifact of the protocol handling errors on Kubuntu, we probably won't get a chance to find a fix until Electron improves support for protocol handling across more distributions of Linux.

**Closed by srinjoym** 2018-10-17 17:05 UTC
Labels: bug

**Comment by neumannm** [comment] 2019-02-20 08:13
Hello, I have the same issue with Classroom Assistant 1.0.3 on Kubuntu 18.04. Same error window from KIO client. On command line, I also get this warning:

    [warn] Failed to set Protocol Handler on Linux: Error: Command failed: xdg-settings set default-url-scheme-handler x-github-classroom classroom-assistant.desktop
    xdg-mime: application argument missing
    Try 'xdg-mime --help' for more information.

I have gnome-keyring installed. Setting the custom protocol handler according to https://github.com/education/classroom-assistant/blob/master/docs/linux-issues.md#kde did not work.

@srinjoym Maybe reopen the issue?

**Comment by bbreinbauer** [comment] 2019-02-27 08:20
I can confirm the issue @neumann describes. Here is some information:
desktop file:
`ll /usr/share/applications/classroom-assistant.desktop
-rw-r--r-- 1 root root 229 26. Dez 10:05 /usr/share/applications/classroom-assistant.desktop`
mime list:
`grep github ~/.config/mimeapps.list 
x-scheme-handler/x-github-classroom=classroom-assistant.desktop
x-github-classroom=classroom-assistant.desktop`
Opening a link with:
`xdg-open x-github-classroom://`
I get an error that no application can be found for the link.

Now something interesting: If I start classroom with an empty LANG environment variable it works:
`LANG="" xdg-open x-github-classroom://`
Maybe this helps finding the root cause of the problem.

**Comment by neumannm** [comment] 2019-02-27 09:28
> Now something interesting: If I start classroom with an empty LANG environment variable it works:
`LANG="" xdg-open x-github-classroom://`
Maybe this helps finding the root cause of the problem.

Great! This works for me, too.

**Comment by lizajane999** [comment] 2019-09-16 02:36
Error is back! I just installed the newest version (1.0.5-1) on my Kubuntu 19.04 system and this error is back. I removed it and downloaded the v1.0.2 from the link above and that version still works (after I manually fix the dependency name issue I just reported in [issue 146](https://github.com/education/classroom-assistant/issues/146) ) .

**Comment by janosg** [comment] 2019-10-28 15:28
I also run into the libgconf2-4 problem reported in #146. @lizajane999 How did you fix this manually?

**Comment by vljubovic** [comment] 2019-10-31 14:42
Same problem on Kubuntu 19.04, version 1.0.5. Workaround: Create a file named ~/.local/share/applications/github-classroom.desktop with following contents:

`[Desktop Entry]`
`Name=Github Classroom`
`Exec=classroom-assistant`
`Type=Application`
`Terminal=false`
`MimeType=x-scheme-handler/x-github-classroom;`

**Comment by EmersonPaduan** [comment] 2020-03-12 01:31
> 
> `[Desktop Entry]`
> `Name=Github Classroom`
> `Exec=classroom-assistant`
> `Type=Application`
> `Terminal=false`
> `MimeType=x-scheme-handler/x-github-classroom;`

I'm using classroom 1.0.5 on Ubuntu 18.04 and this works for me too.

**Comment by pdvrieze** [comment] 2020-05-12 12:06
There is a default file, but it doesn't include the mime type. Adding it solves the issue.
