### ISSUE TITLE
Change display of student name to roster id

### ISSUE THREAD

**Issue by stephaniegiang** [education/classroom-assistant#139] opened 2019-06-20 23:32 UTC
https://github.com/education/classroom/pull/1877 went into classroom that changes the display of the user's name. If the organization has a roster, the student's roster id should be displayed.

**Comment by d12** [comment] 2019-10-02 14:42
Closing as duplicate of https://github.com/education/classroom-assistant/issues/118

**Closed by d12** 2019-10-02 14:42 UTC
